server:
  servlet:
    context-path: /template-framework

spring:
  application:
    name: @parent.name@
  profiles:
      active: @env@
      include:
        - security-@env@
  messages:
    basename: i18n/messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 5S
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

logging:
  config: classpath:logback/logback-@env@.xml

custom-configuration:
  view:
    common-views:
      - {path: /index, name: index}
      - {path: /login, name: login}
      - {path: /menu, name: menu}
    biz-views:
      - {path: /console, name: home/console}
      - {path: /homepage1, name: home/homepage1}
      - {path: /homepage2, name: home/homepage2}
    error-views:
      - {path: /error/400, name: error/400}
      - {path: /error/401, name: error/401}
      - {path: /error/403, name: error/403}
      - {path: /error/404, name: error/404}
      - {path: /error/405, name: error/405}
      - {path: /error/500, name: error/500}
  static:
    resources:
      - {pathPattern: /static/**, location: classpath:/static/}