server:
  port: 8080

spring:
  datasource:
    name: datasource1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_template_framework?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  devtools:
    restart:
      enabled: true

custom-configuration:
  upload:
    image:
      domain: http://localhost/springboottemplate/image/
      path: G:/STATIC/springboot-template/image
  security:
    enabled: false
    super-admin:
      username: admin
      password: admin
    form-login:
      username-param: username
      password-param: password
      login-page: /login
      login-processing-url: /j_spring_secutity_check
      default-success-url: /index
      failure-url: /login
    logout:
      logout-url: /logout
      logout-success-url: /login
      invalidate-session: true
    remember-me:
      remember-me-param: remember-me
      token-validity-seconds: 3600
    permit-match-urls:
      - "/static/**"
      - "/login/**"
      - "/logout/**"
      - "/error/**"
      - "/swagger-ui.html"
      - "/swagger-resources/**"
      - "/swagger/**"