server:
  servlet:
    context-path: /template-framework

spring:
  application:
    name: @parent.name@
  messages:
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: @env@
  mvc:
    throw-exception-if-no-handler-found: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  config: classpath:logback/logback-@env@.xml

custom-configuration:
  view:
    common-views:
      - {path: /index, name: index}
      - {path: /login, name: login}
    biz-views:
      - {path: /console, name: home/console}
      - {path: /homepage1, name: home/homepage1}
      - {path: /homepage2, name: home/homepage2}
    error-views:
      - {path: /error/400, name: error/400}
      - {path: /error/401, name: error/401}
      - {path: /error/403, name: error/403}
      - {path: /error/404, name: error/404}
      - {path: /error/405, name: error/405}
      - {path: /error/500, name: error/500}
  resources:
    - {pathPattern: /static/**, location: classpath:/static/}
  security:
    enabled: false
    super-admin:
      username: admin
      password: admin
    form-login:
      username-param: username
      password-param: password
      login-page: /login
      login-processing-url: /login/submit
      default-success-url: /index
      failure-url: /login
    logout:
      logout-url: /logout
      logout-success-url: /login
      invalidate-session: true
    remember-me:
      remember-me-param: remember-me
      token-validity-seconds: 3600
    permit-match-urls:
      - "/static/**"
      - "/login/**"
      - "/logout/**"
      - "/error/**"
      - "/swagger-ui.html"
      - "/swagger-resources/**"
      - "/swagger/**"