server:
  port: 8444

spring:
  datasource:
    name: datasource1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_thymeleaf_layui_admin?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
  devtools:
    restart:
      enabled: true
