server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    name: primary
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.99.103:3306/springboot_template_framework?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: chang33098
    password: FUCKme619
  redis:
    database: 0
    host: 192.168.99.103
    port: 63799
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

jasypt:
  encryptor:
    password: @project.artifactId@-@env@-privatekey

custom-configuration:
  upload:
    image:
      domain: http://localhost/springboottemplate/image/
      path: G:/STATIC/springboot-template/image