server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    name: datasource1
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.32.119:3306/litemall_dev?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: admin
    password: ssjxbeginning@mysql2019YS#admin
#  datasource:
#    name: datasource1
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot_template_framework?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    username: root
#    password: FUCKme619
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0

custom-configuration:
  upload:
    image:
      domain: http://localhost/springboottemplate/image/
      path: G:/STATIC/springboot-template/image